/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import barba from "@barba/core";
import { gsap } from "gsap/dist/gsap";
import { Cursor } from "../animation/cursor";
import useScroll from "../hooks/useScroll";
import "locomotive-scroll/dist/locomotive-scroll.css";
import { socials } from "../data/social";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:pt-[137px] w-full">
        <section className="flex  lg:items-center lg:justify-between  md:flex-row flex-col w-full container-space">
          <div className="w-full md:w-1/2 md:mb-0 mb-[60px]">
            <h1 className="font-extrabold font-['NeueMachina'] leading-none md:text-[110px] text-[42px] mb-[20px]">
              Frontend
              <br />
              Engineer.
            </h1>
            <p className="lg:mb-[90px] mb-[40px] md:text-[22px] text-[14px] leading-[24px] md:leading-[40px]">
              Hello, Ejiro Asiuwhu here. I focused on developing premium web
              experiences through the lens of design thinking, web performance,
              accessibility, interaction{" "}
            </p>
            <a
              href=""
              className="font-bold flex group md:text-[24px] text-[12px]  items-center "
            >
              <span className="inline-flex mr-[17px] icon-hover link-hover">
                What brought you to Code Lord?
              </span>
              <span className=" icon-hover">
                <svg
                  width="16"
                  height="17"
                  viewBox="0 0 16 17"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M7.00098 1.87029L13.6301 8.49941L7.00098 15.1285M13.6301 8.49941L0.37185 8.49941L13.6301 8.49941Z"
                    stroke="#111111"
                    strokeWidth="2"
                    strokeLinecap="square"
                  />
                </svg>
              </span>
            </a>
          </div>
          <div className="w-full md:w-1/2 flex justify-end items-center flex-col">
            <img
              src="/img/ejiro-asiuwhu.png"
              alt="Ejiro Asiuwhu"
              className="lg:mb-[50px] mb-[30px]"
            />
            <ul className="flex items-center">
              {socials.map((social) => (
                <li key={social.title}>
                  <a
                    href={social.url}
                    aria-label={social.arialLabel}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mr-[60px] text-gray2 font-extrabold"
                  >
                    {social.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
